version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ${PGHOST}
            database: ${PGDATABASE}
            schema: public
            user: ${PGUSER}
            password: ${PGPASSWORD}
            ssl: false
            rawAccess: true
            port: ${PGPORT}
            migrations: false
  web:
    build: ./
    command: npm run dev
    volumes: 
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4444:4444"